[[using-images-other-images-jenkins-slaves]]
= Jenkins Slaves
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

[[overview]]
== Overview
{product-title} provides three images suitable for use as Jenkins slaves: the
*_Base_*, *_Maven_*, and *_Node.js_* images.

The first is a link:https://github.com/openshift/jenkins/tree/master/slave-base[base image] for Jenkins slaves:

 - It pulls in both the required tools (headless Java, the Jenkins JNLP client)
   and the useful ones (including git, tar, zip, and nss among others).
 - It establishes the JNLP slave agent as the entrypoint.
 - It includes the `oc` client tooling for invoking command line operations from
   within Jenkins jobs, and
 - It provides Dockerfiles for both CentOS and RHEL images.

Two additional images that extend the base image are also provided:

* link:https://github.com/openshift/jenkins/tree/master/slave-maven[Maven]
* link:https://github.com/openshift/jenkins/tree/master/slave-nodejs[Node.js]

The Maven and Node.js Jenkins slave images provide Dockerfiles for both CentOS
and RHEL that you can reference when building new slave images. Also note the
`contrib` and `contrib/bin` subdirectories. They allow for the insertion of
configuration files and executable scripts for your image.

IMPORTANT: Use and/or extend an appropriate slave image version for the version
of {product-title} that you are using.  If the `oc` client version embedded in
the slave image is not compatible with the {product-title} version, unexpected
behaviour may result.
ifdef::openshift-enterprise,openshift-dedicated[]
See the xref:../../release_notes/index.adoc#release-versioning-policy[versioning
policy] for more information.
endif::[]

[[jenkins-images]]
== Images

ifdef::openshift-online[]
RHEL 7 images are available through the Red Hat Registry:

----
$ docker pull registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7
$ docker pull registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7
$ docker pull registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7
----
endif::[]

ifndef::openshift-online[]
The {product-title} Jenkins slave images come in two flavors:

*RHEL 7 Based Images*

RHEL 7 images are available through the Red Hat Registry:

----
$ docker pull registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7
$ docker pull registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7
$ docker pull registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7
----

*CentOS 7 Based Images*

These images are available on Docker Hub:

----
$ docker pull openshift/jenkins-slave-base-centos7
$ docker pull openshift/jenkins-slave-maven-centos7
$ docker pull openshift/jenkins-slave-nodejs-centos7
----

To use these images, you can either access them directly from these registries
or push them into your {product-title} Docker registry.
endif::[]

[[configuration-and-customisation]]
== Configuration and Customisation

[[environment-variables]]
=== Environment Variables

Each Jenkins slave container can be configured with the following environment
variables:

* `OPENSHIFT_JENKINS_JVM_ARCH`
+
Set to `x86_64` or `i386` to override the JVM used to host the Jenkins slave
agent.  For memory efficiency, by default the Jenkins slave images dynamically
use a 32-bit JVM if running in a container with a memory limit under 2GiB.

* `JAVA_MAX_HEAP_PARAM` +
`CONTAINER_HEAP_PERCENT` (default: `0.5`, i.e. 50%) +
`JNLP_MAX_HEAP_UPPER_BOUND_MB` +
+
These values control the maximum heap size of the Jenkins slave agent JVM.  If
`JAVA_MAX_HEAP_PARAM` is set (example setting: `-Xmx512m`), its value takes
precedence.  Otherwise, the maximum heap size is dynamically calculated as
`CONTAINER_HEAP_PERCENT`% (example setting: `0.5`, i.e. 50%) of the container
memory limit, optionally capped at `JNLP_MAX_HEAP_UPPER_BOUND_MB` MiB (example
setting: `512`).
+
By default, the maximum heap size of the Jenkins slave agent JVM is set to 50%
of the container memory limit with no cap.

* `JAVA_INITIAL_HEAP_PARAM` +
`CONTAINER_INITIAL_PERCENT`
+
These values control the initial heap size of the Jenkins slave agent JVM.  If
`JAVA_INITIAL_HEAP_PARAM` is set (example setting: `-Xms32m`), its value takes
precedence.  Otherwise, the initial heap size may be dynamically calculated as
`CONTAINER_INITIAL_PERCENT`% (example setting: `0.1`, i.e. 10%) of the
dynamically calculated maximum heap size.
+
By default, the initial heap sizing is left to the JVM.

* `CONTAINER_CORE_LIMIT`
+
If set, specifies an integer number of cores used for sizing numbers of internal
JVM threads.  Example setting: `2`.

* `JAVA_TOOL_OPTIONS` (default: `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true`)
+
Specifies options to be heeded by all JVMs running in this container.  It is not
recommended to override this.

* `JAVA_GC_OPTS` (default: `-XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90`)
+
Specifies Jenkins slave agent JVM garbage collection parameters.  It is not
recommended to override this.

* `JNLP_JAVA_OVERRIDES`
+
Specifies additional options for the Jenkins slave agent JVM.  These options are
appended to all other options, including the Java options above, and may be used
to override any of them if necessary.
